/* swigconfig.h. Generated by cmake from Tools/cmake/swigconfig.h.in */

#define HAVE_CXX17 1

/* define if the Boost library is available */
#define HAVE_BOOST

/* Define if you have PCRE library */
#define HAVE_PCRE 1

/* Name of package */
#define PACKAGE "swig"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://www.swig.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "swig"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "swig 5.0.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "swig"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "5.0.5"

/* The size of `void *', as computed by sizeof. */
/* #undef SIZEOF_VOID_P */

/* Define to 1 if all of the C90 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Compiler that built SWIG */
#define SWIG_CXX "/usr/bin/c++"

/* Directory for SWIG system-independent libraries */
#define SWIG_LIB "/usr/local/share/swig/5.0.5"

/* Directory for SWIG system-independent libraries (Unix install on native
   Windows) */
#define SWIG_LIB_WIN_UNIX ""

/* Platform that SWIG is built for */
#define SWIG_PLATFORM "Linux"

/* Version number of package */
#define VERSION "5.0.5"


/* Deal with attempt by Microsoft to deprecate C standard runtime functions */
#if defined(_MSC_VER)
# define _CRT_SECURE_NO_DEPRECATE
#endif

